spring:
  application:
    name: api
  data:
    mongodb:
      uri: mongodb://nexusfc:nexusfc123@localhost:27017/
      database: nexusfc
      auto-index-creation: false

api:
  security:
    token:
      secret: ${JWT_SECRET:nexusfc-secret}

gemini:
  api:
    key:
