logging:
  level:
    org:
      springframework:
        transaction: DEBUG
        data:
          mongodb: DEBUG

spring:
  application:
    name: api
  data:
    mongodb:
      uri: mongodb://localhost:27017/nexusfc?replicaSet=rs0&directConnection=true

api:
  security:
    token:
      secret: ${JWT_SECRET:nexusfc-secret}

gemini:
  api:
    key:
